// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
//APPLICATION
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONT = 'CHANGE_FONT';
export const FORCE_APPEARANCE = 'FORCE_APPEARANCE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const TEMP_AUTH_DATA = 'TEMP_AUTH_DATA';
export const LOCATION = 'LOCATION';
export const COUNSELOR_ACCOUNT_TEMP_DETAILS = 'COUNSELOR_ACCOUNT_TEMP_DETAILS';
export const WEB3_DETAILS = 'WEB3_DETAILS';
export const INTRO_SHOWN_ALREADY = "INTRO_SHOWN_ALREADY";
export const TOUR_COMPLETION = "TOUR_COMPLETION";